name: Docs WorkFlow - Develop Tag ğŸ“š

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pages: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: ğŸ“¦ Install mkdocs-material
        run: pip install "mkdocs-material[all]"
      - name: ğŸ“¦ Install mkdocstrings[python]
        run: pip install "mkdocstrings[python]"
      - name: ğŸ“¦ Install mkdocs-material[imaging]
        run: pip install "mkdocs-material[imaging]"
      - name: ğŸ“¦ Install mike
        run: pip install "mike"
      - name: ğŸ“¦ Install mkdocs-git-revision-date-localized-plugin
        run: pip install "mkdocs-git-revision-date-localized-plugin"
      - name: ğŸ“¦ Install JupyterLab
        run: pip install jupyterlab
      - name: ğŸ“¦ Install mkdocs-jupyter
        run: pip install mkdocs-jupyter
      - name: ğŸ“¦ Install mkdocs-git-committers-plugin-2
        run: pip install mkdocs-git-committers-plugin-2
      - name: âš™ï¸ Configure git for github-actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: ğŸš€ Deploy MkDoc-Material with mike
        run: |
          MKDOCS_GIT_COMMITTERS_APIKEY=${{ secrets.GITHUB_TOKEN }} mike deploy --push develop
