name: Docs WorkFlow - Develop Tag ğŸ“š

on:
  push:
    branches:
      - develop
  workflow_dispatch:

# Ensure only one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref}}
  cancel-in-progress: true

# Restrict permissions by default
permissions:
  contents: write  # Required for committing to gh-pages
  pages: write    # Required for deploying to Pages
  pull-requests: write  # Required for PR comments

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: ğŸ”„ Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0
          
      - name: ğŸ Set up Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v5.0.0
        with:
          python-version: '3.10'
          
      - name: ğŸ“¦ Install dependencies
        run: |
          pip install "mkdocs-material==9.5.2" \
                    "mkdocstrings[python]==0.24.0" \
                    "mkdocs-material[imaging]==9.5.2" \
                    "mike==2.0.0" \
                    "mkdocs-git-revision-date-localized-plugin==1.2.1" \
                    "jupyterlab==4.0.9" \
                    "mkdocs-jupyter==0.24.6" \
                    "mkdocs-git-committers-plugin-2==2.2.2"
          
      - name: âš™ï¸ Configure git for github-actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: ğŸš€ Deploy MkDoc-Material with mike
        run: |
          MKDOCS_GIT_COMMITTERS_APIKEY=${{ secrets.GITHUB_TOKEN }} mike deploy --push --update-aliases develop latest
