name: Publish Supervision Pre-Releases to PyPI and TestPyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+a[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+b[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+rc[0-9]"
  workflow_dispatch:

permissions: {} # Explicitly remove all permissions by default

jobs:
  build-and-publish-pre-release:
    name: Publish  Pre-releasePackage
    runs-on: ubuntu-latest
    environment: test
    timeout-minutes: 10
    permissions:
      id-token: write # Required for PyPI publishing
      contents: read # Required for checkout
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: ğŸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ“œ Setup Poetry
        uses: abatilo/actions-poetry@e78f54a89cb052fff327414dd9ff010b5d2b4dbd # v3.0.1

      - name: ğŸ—ï¸ Build source and wheel distributions
        run: |
          poetry install --with=build
          poetry build
          poetry run twine check --strict dist/*

      - name: ğŸš€ Publish to PyPi
        uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
        with:
          attestations: true

      - name: ğŸš€ Publish to Test-PyPi
        uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true
