name: Publish Supervision Releases to PyPI and TestPyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+[0-9]+.[0-9]"
  workflow_dispatch:

permissions: {}  # Explicitly remove all permissions by default

jobs:
  build-and-publish-pre-release:
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 15
    permissions:
      id-token: write  # Required for PyPI publishing
      contents: read   # Required for checkout
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ github.head_ref }}
          
      - name: ğŸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v5.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ—ï¸ Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*

      - name: ğŸš€ Publish to PyPi
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11

      - name: ğŸš€ Publish to Test-PyPi
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
        with:
          repository-url: https://test.pypi.org/legacy/
