name: ğŸ§ª Docs Test WorkFlow ğŸ“š

on:
  pull_request:
    branches: [main, develop]

jobs:
  docs-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name:  ğŸ—ï¸ Install dependencies and Test Docs Build
        run: |
          python -m pip install --upgrade pip
          pip install "mkdocs-material" "mkdocstrings[python]" "mkdocs-material[imaging]" mike "mkdocs-git-revision-date-localized-plugin" jupyterlab mkdocs-jupyter mkdocs-git-committers-plugin-2
          mkdocs build --verbose
