name: ğŸ§ª Docs Test WorkFlow ğŸ“š

on:
  pull_request:
    branches: [main, develop]

# Restrict permissions by default
permissions:
  contents: read  # Required for checkout
  checks: write  # Required for test reporting

jobs:
  docs-build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ğŸ”„ Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: ğŸ Set up Python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v5.0.0
        with:
          python-version: '3.10'

      - name: ğŸ“œ Setup Poetry
        uses: abatilo/actions-poetry@e78f54a89cb052fff327414dd9ff010b5d2b4dbd # v3.0.1
        
      - name: ğŸ—ï¸ Install dependencies
        run: |
          python install --group docs
          
      - name: ğŸ§ª Test Docs Build
        run: |
          mkdocs build --verbose
