name: ğŸ§ª Docs Test WorkFlow ğŸ“š

on:
  pull_request:
    branches: [main, develop]

jobs:
  docs-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout code
        uses: actions/checkout@v4
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: ğŸ“¦ Install mkdocs-material
        run: pip install "mkdocs-material[all]"
      - name: ğŸ“¦ Install mkdocstrings[python]
        run: pip install "mkdocstrings[python]"
      - name: ğŸ“¦ Install mkdocs-material[imaging]
        run: pip install "mkdocs-material[imaging]"
      - name: ğŸ“¦ Install mike
        run: pip install "mike"
      - name: ğŸ“¦ Install mkdocs-git-revision-date-localized-plugin
        run: pip install "mkdocs-git-revision-date-localized-plugin"
      - name: ğŸ“¦ Install JupyterLab
        run: pip install jupyterlab
      - name: ğŸ“¦ Install mkdocs-jupyter
        run: pip install mkdocs-jupyter
      - name: ğŸ“¦ Install mkdocs-git-committers-plugin-2
        run: pip install mkdocs-git-committers-plugin-2
      - name: ğŸ§ª Test documentation build
        run: mkdocs build --verbose
